### ISSUE TITLE
persistence.storageClass value is not applied to every PersistenceVolumeClaim

### ISSUE THREAD

**Issue by perrefe** [zammad/zammad-helm#139]
Version of Helm and Kubernetes:
1.24, helm 3.8.2

What happened:
After installing the chart version 6.7.0 and 6.7.1 I've noticed that the only PVC that gets the attribute storageClassName configured in values.yml (as persistence.storageClass) is the release-name-zammad StatefulSet.

What you expected to happen:
All the four PVC needs to have the correct storageClass defined via values. 

How to reproduce it (as minimally and precisely as possible):
with values:
```
persistence:
  storageClass: host-storage #This is the name of my storageClass
```

run:
`helm template --debug -f values.yml zammad/zammad`

Anything else we need to know:
I have defined storageclass and volumes like this:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: host-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zammad-postgres-pv
spec:
  storageClassName: host-storage
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv/zammad/postgres"
```

The other pv's are the same, with their own metadata and path
