### ISSUE TITLE
unsuitable default values for bitnami ES

### ISSUE THREAD

**Issue by masterkain** [zammad/zammad-helm#154]
I upgraded to a helm chart that now contains bitnami ES and had to run a modest reindex, ES kept dying during this phase.

Following an investigation it seems to be related to heap memory issues, to fix this:

```
  values:
    elasticsearch:
      master:
        heapSize: 512m
```

instead of the default 256m - maybe it's worth setting this value in the default values directly.
