### ISSUE TITLE
Existing volumeclaim creates volume with wrong name

### ISSUE THREAD

**Issue by MTRNord** [zammad/zammad-helm#201]
https://github.com/zammad/zammad-helm/blob/3f7da1e5683041693bc0b76215d48537a584d8a3/zammad/templates/statefulset.yaml#L417

Hi,

This seems to be an oversight but when using an existing volumeClaim the volume is missing the `-var` suffix which causes the container to not start.

**Comment by monotek** [comment]
whats the exact error message?

**Comment by MTRNord** [comment]
Notably the volumes in the statefulset are defined like this:

```
      volumes:                                                                                                                                                                                                       
      - configMap:                                                                                                                                                                                                   
          defaultMode: 420                                                                                                                                                                                           
          name: zammad-nginx                                                                                                                                                                                         
        name: zammad-nginx                                                                                                                                                                                           
      - configMap:                                                                                                                                                                                                   
          defaultMode: 493                                                                                                                                                                                           
          name: zammad-init                                                                                                                                                                                          
        name: zammad-init                                                                                                                                                                                            
      - emptyDir:                                                                                                                                                                                                    
          sizeLimit: 100Mi                                                                                                                                                                                           
        name: zammad-tmp                                                                                                                                                                                             
      - name: zammad                                                                                                                                                                                                 
        persistentVolumeClaim:                                                                                                                                                                                       
          claimName: zammad-var-zammad-0-nfs-temp
```

while referenced as:

```
        volumeMounts:                                                                                                                                                                                                
        - mountPath: /opt/zammad/var                                                                                                                                                                                 
          name: zammad-var                                                                                                                                                                                           
        - mountPath: /docker-entrypoint.sh                                                                                                                                                                           
          name: zammad-init                                                                                                                                                                                          
          readOnly: true                                                                                                                                                                                             
          subPath: postgresql-init
```

where `zammad-var` previously mapped to the now `zammad` called volume
