### ISSUE TITLE
Postgresql credentials should be percent encoded

### ISSUE THREAD

**Issue by hsahmed** [zammad/zammad-helm#251]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes: 1.28.2
Zammad Chart: 10.2.1

**What happened**:
It is not possible to use a Postgresql password containing any characters that have a special meaning within the URL (& : % / and possible others).

**What you expected to happen**:
Any characters in the password or other elements of the URL that have special meaning within the URL should percent-encoded. 

**How to reproduce it** (as minimally and precisely as possible):
Install the Helm release using the following values:
```
zammadConfig:
  postgresql:
    pass: "zammad:test"

postgresql:
  auth:
    postgresPassword: "zammad:test"
    password: "zammad:test"
    replicationPassword: "zammad:test"
```

**Anything else we need to know**:
Helm has a template function `urlquery` that can be used to encode the values https://helm.sh/docs/chart_template_guide/function_list/#urlquery
