### ISSUE TITLE
S3 storage: Not using correct credentials when using existing secret for minio auth

### ISSUE THREAD

**Issue by stijnbrouwers** [zammad/zammad-helm#252]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**Version of Helm and Kubernetes**:
Helm: v3.14.0
Kubernetes: v1.20

**What happened**:
When I use an existing secret for minio auth, the credentials are not reflected in the S3 url passed to Zammad. Instead, both the username and password are "zammadadmin"

**What you expected to happen**:
The the S3 url contains the correct credentials instead of zammadadmin for both the username and password

**How to reproduce it** (as minimally and precisely as possible):
Use the following config
```
zammadConfig:
  minio:
    enabled: true
minio:
  persistence:
    size: 32Gi
  auth:
    rootUser: zammadadmin
    rootPassword: zammadadmin
    existingSecret: zammad-minio
  defaultBuckets: zammad
  disableWebUI: false
```

**Anything else we need to know**:
/
