### ISSUE TITLE
S3 storage with existing auth not working in combination with argocd

### ISSUE THREAD

**Issue by stijnbrouwers** [zammad/zammad-helm#255]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**Version of Helm and Kubernetes**:
Helm: v3.14.0
Kubernetes: v1.20

**What happened**:
When I use an existing secret for minio auth the deployment is not working through argocd.
This is because argocd does not support the helm lookup-function.

**What you expected to happen**:
To be able to deploy the chart using argocd

**How to reproduce it** (as minimally and precisely as possible):
Use the following config
```
zammadConfig:
  minio:
    enabled: true
minio:
  persistence:
    size: 32Gi
  auth:
    rootUser: zammadadmin
    rootPassword: zammadadmin
    existingSecret: zammad-minio
  defaultBuckets: zammad
  disableWebUI: false
```

**Anything else we need to know**:
/
