### ISSUE TITLE
How to automate restart?

### ISSUE THREAD

**Issue by mueller-ma** [zammad/zammad-helm#285]
**Version of Helm and Kubernetes**:
- RKE2 1.28.11
- Helm v3.14.4

**What happened**:

I changed a setting via the UI and a pop appeared:

> Zammad benötigt einen Neustart!
> Systemeinstellungen wurden geändert, bitte starten Sie alle Zammad-Prozesse neu. Wenn Sie diesen Vorgang automatisieren wollen, können Sie folgende Umgebungsvariable setzen: APP_RESTART_CMD="/path/to/your_app_script.sh restart".

How can I automate a restart when running in Kubernetes? When Zammad detects that it runs in Kubernetes, it could just terminate and Kubernetes will restart the containers.

**Comment by mgruner** [comment]
@mueller-ma I am not aware of a possible automation at this point. This would also be interesting for our docker-compose stack.

A main issue is that all containers would have to be restarted, including the scheduler for example. Right now this is not possible. Let us know if you have any ideas how this can be achieved - this would be a feature request, or you could contribute.

**Comment by monotek** [comment]
If zammad itself is aware of it, it could create a kubernetes job, which uses a kubectl container to do a "kubectl -n zammad-namespace rollout restart deployment zammad".

For this the serviceaccount would need a rolebinding, which give these kube api the needed permissions.

This could look like:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zammad-restart
  namespace: zammad
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    resourceNames: ['zammad']
    verbs: ['get', 'patch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zammad-restart
  namespace: zammad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zammad-restart
subjects:
  - kind: ServiceAccount
    name: zammad
    namespace: zammad

---
apiVersion: batch/v1
kind: Job
metadata:
  name: zammad-restart
  namespace: zammad
  labels:
    app: zammad-restart
spec:
  template:
    metadata:
      labels:
        app: zammad-restart
    spec:
      serviceAccountName: zammad-restart
      containers:
        - name: restart
          image: bitnami/kubectl:1.29.6
          args:
            - rollout
            - restart
            - deployment
            - zammad
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "32Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10011
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: OnFailure

```
