### ISSUE TITLE
apps/v1

### ISSUE THREAD

**Issue by sfxworks** [zammad/zammad-helm#29]
```
C:\Users\shaba>helm upgrade --install zammad zammad/zammad --namespace=zammad
Release "zammad" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
```

I can't find any references to apps/v1beta1 in the chart. It seems like it's coming from remote dependencies.  Unfortunentally, this means I can't install this on my cluster since its a later version.

**Version of Helm and Kubernetes**:
```
C:\Users\shaba>helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

C:\Users\shaba>kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
Deployment failed

**What you expected to happen**:
Deployment succeeds

**How to reproduce it** (as minimally and precisely as possible):
Deploy on a cluster where apps/v1 is active

**Anything else we need to know**:
Statefulset was promoted to apps/v1 ~1.16 I believe. May be able to replicate there if that helps.

**Comment by monotek** [comment]
Fix will be made available in the next days from #36c3 :)

**Comment by monotek** [comment]
You could download the chart & update the requirements as a workaround for now.
Not sure if we manage to publish a new version this year as we're struggling with the new ci pipeline.

**Comment by sfxworks** [comment]
The thing is it seems to be coming from other chats. This chart seems to call on others for postgre/elastic search/another. Having a hard time getting those.

**Comment by sfxworks** [comment]
Ah I see what you mean
```
dependencies:
  - name: elasticsearch
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.32.1
    condition: useElasticsearch
  - name: memcached
    version: 3.2.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: useMemcached
  - name: postgresql
    version: 8.1.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: usePostgresql
```

Updated requirements and all and ran `helm dep update`
