### ISSUE TITLE
Non-default passwords not working

### ISSUE THREAD

**Issue by Gerharddc** [zammad/zammad-helm#339]
Hi, I am trying to use non-default passwords for postgres etc. to have a more secure system but it seems this stack refuses to work when I try to change password. Currently the way I am doing that is by having a file named `zammad-values.yaml.secret` with contents such as:

```
...
zammadConfig:
  elasticsearch:
    pass: uIe474UhL4LmzQxYuxYU

  postgresql:
    pass: hVl2NiL1i1JLNc11L318

  redis:
    pass: IDUpqHvDnq8p69Zy6Fdm
...
```

Then I deploy it with `helm upgrade --install zammad zammad/zammad -f zammad-values.yaml.secret` and after a while I am greeted with the following situation:

```
NAME                                  READY   STATUS             RESTARTS        AGE
zammad-elasticsearch-master-0         1/1     Running            0               10m
zammad-memcached-575cf49bd6-mbn8l     1/1     Running            0               10m
zammad-nginx-7f5fd76479-x9v97         0/1     Running            0               10m
zammad-postgresql-0                   1/1     Running            0               10m
zammad-railsserver-85db4967c7-9s5kt   0/1     CrashLoopBackOff   6 (3m11s ago)   10m
zammad-redis-master-0                 1/1     Running            0               10m
zammad-scheduler-7c5d78fb88-5vrzz     0/1     CrashLoopBackOff   6 (3m25s ago)   10m
zammad-websocket-78ff786dd8-b9nzq     0/1     CrashLoopBackOff   6 (3m31s ago)   10m
```

When inspecting the logs of one of the crashing pods, it is clear that it is not managing to log into postgres:

```
! Unable to load application: ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: zammad.

Please check your database configuration to ensure the username/password are valid.

bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
/usr/local/bundle/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:65:in `rescue in new_client': There is an issue connecting to your database with your username/password, username: zammad. (ActiveRecord::DatabaseConnectionError)

Please check your database configuration to ensure the username/password are valid.
```

When I don't try to change the passwords then everything works just fine so clearly there is an issue with how they are handled.

P.S. I first tried settings custom passwords by updating the following "values" instead:

```
secrets:
  autowizard:
    useExisting: true
    secretKey: password
    secretName: autowizard-creds
  elasticsearch:
    useExisting: true
    secretKey: password
    secretName: elastic-creds
  postgresql:
    useExisting: true
    secretKey: password
    secretName: postgresql-creds
  redis:
    useExisting: true
    secretKey: password
    secretName: redis-creds
```

But this resulted in the same issue. After looking through the code for this chart, I realized there appears to be no mechanism to feed these secrets into the postgres etc. pods so that's why I ended up directly changing the "zammadConfig" fields instead as this appears to be needed in any case. There does appear to be the opposite mechanism though i.e. if you only set these fields then the helm chart creates matching secrets for you. It would have been much nicer if it were possible to only have to set the secrets though.

**Comment by MrGeneration** [comment]
The postgresql stack doesn't care if you change passwords, it only creates the user with the set password once as far as I'm aware. You gotta change it in the container.

**Comment by Gerharddc** [comment]
Thanks @MrGeneration , that is very possible indeed. However, even making these changes before deploying a fresh chart has the same problem. In the case of a fresh deploy I would expect it to create the postgres container with the password provided in zammadConfig:postgresql:pass or am I missing something?

**Comment by Gerharddc** [comment]
Ah wait, it seems I forgot to update the "auth" values for the other stacks since I only updated zammadConfig. Let met try updating them too.

**Comment by Gerharddc** [comment]
Ok so in the end I was able to fix this by defining a `zammad-values.yaml` such as:

```
secrets:
  autowizard:
    useExisting: true
    secretKey: password
    secretName: autowizard-creds
  elasticsearch:
    useExisting: true
    secretKey: password
    secretName: elastic-creds
  postgresql:
    useExisting: true
    secretKey: password
    secretName: postgresql-creds
  redis:
    useExisting: true
    secretKey: password
    secretName: redis-creds

elasticsearch:
  security:
    existingSecret: elastic-creds
    existingSecretPasswordKey: password

postgresql:
  auth:
    postgresPassword: null
    password: null
    replicationPassword: null

    existingSecret: postgresql-creds
    secretKeys:
      adminPasswordKey: password
      userPasswordKey: password
      replicationPasswordKey: password

redis:
  auth:
    password: null
    existingSecret: redis-creds
    existingSecretPasswordKey: password
```

The key was to also update the "auth" values.
