### ISSUE TITLE
unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext when installing zammad

### ISSUE THREAD

**Issue by alionar** [zammad/zammad-helm#40]
**Is this a request for help?**: Yes

---
**Version of Helm and Kubernetes**:
```
kubectl version 1.15
helm version 3.1.1
```

**What happened**:
When i installed zammad with helm install using this command,
```helm install --set postgresql.enable=false --set envConfig.postgresql.host=sqlproxy-service-ds1 --set env.Config.postgresql.port=3306 --set envConfig.postgresql.pass=xxxxxx my-zammad zammad/zammad --version 2.0.5 --namespace zammad```

i got this error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error vali
dating data: [ValidationError(StatefulSet.spec.template.spec.containers[1].securityContext): unk
nown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(StatefulSet.spec.tem
plate.spec.containers[2].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.Securit
yContext, ValidationError(StatefulSet.spec.template.spec.containers[3].securityContext): unknown

field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(StatefulSet.spec.templat
e.spec.initContainers[1].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.Securit
yContext, ValidationError(StatefulSet.spec.template.spec.initContainers[2].securityContext): unk
nown field "fsGroup" in io.k8s.api.core.v1.SecurityContext]
```

**What you expected to happen**:
Zammad will be running on my cluster in GKE

**How to reproduce it** (as minimally and precisely as possible):
- Create new cluster and connect it
- `helm repo add zammad https://zammad.github.io`
- `helm repo update`
- Deploy on cluster with command above

**Anything else we need to know**:
I want to use our postgresql instance v9.6 @ GCP CloudSQL for zammad prod db via cloudsqlproxy (same namespace).

sqlproxy-deployment.yaml
```
# https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md
# 1. kubectl create secret generic service-account-token --from-file=credentials.json=$HOME/kubernetes/cloudsql_proxy/credentials.json --namespace zammad
# 2. kubectl apply -f sqlproxy-deployment.yaml --namespace zammad
# 3. kubectl apply -f sqlproxy-services.yaml --namespace zammad

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsqlproxy
    spec:
      containers:
       # Make sure to specify image tag in production
       # Check out the newest version in release page
       # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
      - image: b.gcr.io/cloudsql-docker/gce-proxy:latest
       # 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
        imagePullPolicy: Always
        name: cloudsqlproxy
        command:
        - /cloud_sql_proxy
        - -dir=/cloudsql
        - -instances=<PROJECT_ID>:<ZONE>:<SQL_INSTANCE>=tcp:0.0.0.0:3306
        - -credential_file=/credentials/credentials.json
        # set term_timeout if require graceful handling of shutdown
        # NOTE: proxy will stop accepting new connections; only wait on existing connections
        - term_timeout=10s
        lifecycle:
          preStop:
            exec:
              # (optional) add a preStop hook so that termination is delayed
              # this is required if your server still require new connections (e.g., connection pools)
              command: ['sleep', '10']
        ports:
        - name: port-ds1
          containerPort: 3306
        volumeMounts:
        - mountPath: /cloudsql
          name: cloudsql
        - mountPath: /credentials
          name: service-account-token
      volumes:
      - name: cloudsql
        emptyDir:
      - name: service-account-token
        secret:
          secretName: service-account-token
```

sqlproxy-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: sqlproxy-service-ds1
spec:
  ports:
  - port: 3306
    targetPort: port-ds1
  selector:
    app: cloudsqlproxy
```

**Comment by lukaszgryglicki** [comment]
Had the same problem:
Security context and PodSecurity context are not the same objects.
I had
```
         image: '{{ .Values.postgresImageName }}'
         imagePullPolicy: '{{ .Values.imagePullPolicy }}'
        securityContext:
          fsGroup: 999
         ports:
```
at the container level, while it seems that `fsGroup` can only be set at the pod level (one up)
Moved that to `pod` spec level fixe dthe issue:
```
     spec:
      securityContext:
        fsGroup: 999
       serviceAccountName: '{{ .Values.postgresSvcName }}'
       volumes:
```
