### ISSUE TITLE
Persistent volumes - how to control what is created and which size

### ISSUE THREAD

**Issue by dinonovak** [zammad/zammad-helm#68]
Hi,

I would like to control how persistent volumes are created during the setup process.
I can see that template is supporting:
persistence.storageClass:
persistence.existingClaim:

When running the helm on rancher beside this PV (zammad-data) that I can manually specifiy in template variables, I can see that there are two additional volumes created so in total it looks like:

zammad-postgresql (container in workload zammad-postgresql) is claiming: zammad:data-zammad-postgresql-0
elasticsearch (container in workload zammad-master) is claiming: zammad:zammad-master-zammad-master-0
zammad-railsserver (container in workload zammad) is claiming: zammad:zammad-data  - THIS ONE IS CONTROLLED BY HELM TEMPLATE

I would like to have control over postgresql and elasticsearch claims so that I can attach existing preconfigured volumes.
Thanx,
D

**Comment by monotek** [comment]
These are dependency charts. See requirements file.
They have there own configuration. Just add it to the bottom of the values file.

**Comment by dinonovak** [comment]
OK,
so in the requirements.yaml I can see:
```
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.9.1
    condition: elasticsearch.enabled
```

I opened elasticsearch helm chart and in values.yaml I can see:
```
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi
```

so how do I pass this parameter from zammad HELM template.
Do I need to create my own template and add this to values.yaml or I can inject them directly by specifying values so in this case it would be:
```
elasticsearch.volumeClaimTemplate.storageClassName
elasticsearch.volumeClaimTemplate.resources.requests.storage 
```
