### ISSUE TITLE
Installing zammad failed because elasticsearch-init is running as ROOT (zammad-master-0).

### ISSUE THREAD

**Issue by ajeetratnu** [zammad/zammad-helm#87]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
Helm version
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
Kubectl version
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-XXX", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"dirty", BuildDate:"2020-10-15T07:10:10Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
Zammad installation fails due to ROOT image of elasticsearch-init as cluster has pod security policy to not allow root or privileged images.

**What you expected to happen**:
Elastic search should run as NON ROOT image

**How to reproduce it** (as minimally and precisely as possible):
Install using helm with below images:
zammad/zammad-docker-compose:zammad-4.0.0-7
zammad/zammad-docker-compose:zammad-elasticsearch-4.0.0-7

Results in error
```
create Pod zammad-master-0 in StatefulSet zammad-master failed error: pods "zammad-master-0" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

**Anything else we need to know**:
Similar issue was fixed for zammad-init container for bug #82.

**Comment by monotek** [comment]
Elasticsearch is installed via dependency chart. See:
https://github.com/zammad/zammad-helm/blob/master/zammad/Chart.yaml#L18

So you would need to configure elasticsearch related stuff via config values of that chart. See:
https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml#L110

**Comment by ajeetratnu** [comment]
> Elasticsearch is installed via dependency chart. See:
> https://github.com/zammad/zammad-helm/blob/master/zammad/Chart.yaml#L18
> 
> So you would need to configure elasticsearch related stuff via config values of that chart. See:
> https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml#L110

Hi, I tried it by creating my-values.yaml file like below. But its not taking these values and always failing with same error. Do I have to give it somewhere else?
```
image:
  repository: my-repo-path/zammad-docker-compose
  tag: zammad-4.0.0-7
  pullPolicy: Always
  imagePullSecrets: 
   - name: "my-pull-secret"

elasticsearch:
  image: "my-repo-path/zammad-docker-compose"
  imageTag: "zammad-elasticsearch-4.0.0-7"
  imagePullPolicy: Always
  podSecurityPolicy:
    spec:
      privileged: false
      runAsUser:
        rule: MustRunAsNonRoot
  
memcached:
  image:
      registry: reg-dhc.app.corpintra.net
      repository: mbvm/memcached

postgresql:
  image:
      registry: reg-dhc.app.corpintra.net
      repository: mbvm/postgresql
```

**Comment by monotek** [comment]
You can try the following command to see, if your config works:

```
helm template . -f your-values.yaml
```

I've tried your config and the podSecurityPolicy in the elasticsearch statefuleset took the values:

```
  podSecurityPolicy:
    spec:
      privileged: false
      runAsUser: MustRunAsNonRoot
```
But questions about configuring the elasticsearch chart are out of scope of the zammad chart.

Please ask in: https://github.com/elastic/helm-charts

Closing.
